### ISSUE TITLE
Track flagged individual add variable somewhere

### ISSUE THREAD

**Issue by Alcharyx** [Cranfield-GDP3/TACTUS-live#5]
Currently working on the visualisation with open cv and it would be great to store a bool variable somewhere that is set to true if the individual did a flagged action to keep his bounding box red even after the action is finished (as professor advised)

**Comment by Alcharyx** [comment]
I though of saving it in feature_tracker.deepsort.tracker.tracks what do you think @MarcBresson ?

**Comment by MarcBresson** [comment]
We should avoid modifying a third party library too much, as this would make future deepsort upgrade too hard.
I think a new custom object could be created in tactus_model that would save the prediction that are not neutral in the following manner:

```python
class PredTracker:
    def __init__(self):
        self.tracker: dict[int, dict]
    
    def example(self):
        self.tracker = {
            1: {
                "label": "kicking",
                "timestamp": 18123876247,
                "pos_x": 245,
                "pos_y": 657,
            }
        }
```

**Comment by Alcharyx** [comment]
Maybe add a tracking id field ?

**Comment by MarcBresson** [comment]
it is in the dictionary key 
{
**1**: {
"lab...

**Comment by MarcBresson** [comment]
added in tactus_model https://github.com/Cranfield-GDP3/TACTUS-model/commit/d2ae5b9f0607ffe257e316ce8247329020aecf8b
