### ISSUE TITLE
Remove unexistant track id in tracker.py

### ISSUE THREAD

**Issue by Alcharyx** [Cranfield-GDP3/TACTUS-live#6]
There is currently a bug where the programm tries to remove from rolling window a track id that doesn't exist, currently we have this quick fix checking if the track id exist but maybe we could make it so that it doesn't try to remove something not existing first.
![image](https://user-images.githubusercontent.com/104650995/232203383-d54bc09e-865b-461a-b611-8abb5dfcff9f.png)

**Comment by Alcharyx** [comment]
this fix is not pushed yet I think btw

**Comment by MarcBresson** [comment]
This *was* coming from the fact that we were not adding not-confirmed track into the feature tracker, but that they were still appearing in the id_to_remove list.

In the new version, we add every tracks in the feature_tracker
